### ISSUE TITLE
مشکل در ایجاد کاربر با کاراکترهای فارسی

### ISSUE THREAD

**Issue by lolibooki** [AriaMoradi/skyroom-python#1]
وقتی که متد 
createUser 
با پارامتری که دارای عبارات فارسی باشه فراخوانی بشه ارور با استاتوس 14 میده که نام کاربری باید بیشتر از 2 حرف و شامل حروف و اعداد باشه

params = {"username": "تست", 'password': "12345", 'nickname': "تستتست", 'status': 1, 'is_public': False}

**Comment by lolibooki** [comment]
> وقتی که متد
> createUser
> با پارامتری که دارای عبارات فارسی باشه فراخوانی بشه ارور با استاتوس 14 میده که نام کاربری باید بیشتر از 2 حرف و شامل حروف و اعداد باشه

**Comment by AriaMoradi** [comment]
فرض میکنیم که مشکل خود به خود درست شد؟
@lolibooki
